apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-controller
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["{{ .Release.Name }}"]
  verbs: ["delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  resourceNames: ["default"]
  verbs: ["get", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create"]
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["get"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ include "awscli2-kubectl.serviceAccountName" . }}
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ .Release.Name }}-controller
  apiGroup: ""
