FROM debian:buster-slim

ARG AWS_VERSION="2.4.5"
ARG KUBE_VERSION="v1.23.2"

    # awscli2
RUN apt-get update; \
    apt-get install unzip curl -y; \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"; \
    unzip awscliv2.zip; \
    ./aws/install; \
    # kubectl
    curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.22.6/2022-03-09/bin/linux/amd64/kubectl ;\
    chmod +x kubectl; \
    cp ./kubectl /bin/kubectl